version: "3.3"
services:
    swagger-ui:
        image: swaggerapi/swagger-ui
        container_name: "swagger-ui"
        networks:
            serviceNetwork:
                ipv4_address: 192.168.2.252
        ports:
            - "localhost:8082:8080"
        expose:
            - "8080"
        volumes:
            - ./openapi.yml:/home/docs/openapi.yml
        environment:
            SWAGGER_JSON: /home/docs/openapi.yml
            # API_URL: "/home/docs"
        restart: always
networks:
    serviceNetwork:
        name: serviceNetwork
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.2.0/24
