version: "3.3"
services:
    swagger-ui:
        image: swaggerapi/swagger-ui
        container_name: "swagger-ui"
        ports:
            - "8082:8080"
        volumes:
            - ./openapi.yml:/openapi.yml
        environment:
            SWAGGER_JSON: /openapi.yml
            # API_URL: ""
        restart: always
